version: '3.8'
volumes:
  database_vol:
  cassandra_data:
    driver: local
  cassandra2_data:
    driver: local
  cassandra3_data:
    driver: local
services:
  app:
    build: .
    command: yarn start
    volumes:
      - .:/usr/app
    depends_on:
      - db
      - cassandra
      - cassandra2
      - cassandra3
    ports:
      - '3333:3333'
    environment: 
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DATABASE: ${DATABASE_DATABASE}
  db:
    image: postgres:latest
    volumes:
      - database_vol:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$DATABASE_USERNAME"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    ports:
      - '5432:5432'
  cassandra:
    image: cassandra:latest
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - cassandra_data:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  cassandra2:
    image: cassandra:latest
    ports:
      - 7001:7000
      - 9043:9042
    volumes:
      - cassandra2_data:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
  cassandra3:
    image: cassandra:latest
    ports:
      - 7002:7000
      - 9044:9042
    volumes:
      - cassandra3_data:/bitnami
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M